#%RAML 1.0 DataType
type: object
properties:
  status: string
  errorCode: integer
  errorDescription: string

example:
  value:
    status: failure
    errorCode: 400
    errorDescription: "HTTP Error 400"