#%RAML 1.0 DataType
type: object
properties:
  StudentName: string    
  StudentID: integer
  StudentAddress: string
  StudentPhone: string
  StudentActive: string
  StudentYear: integer
  StudentSemester: integer
  
example:
  value:
    StudentName: "Name 1"
    StudentID: 101
    StudentAddress: "Addr 1"
    StudentPhone: "9944556611"
    StudentActive: "A"
    StudentYear: 2002
    StudentSemester: 1
    